services:
  dakosys:
    image: ghcr.io/sahara101/dakosys:latest
    container_name: dakosys
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /kometa:/kometa
    command: --help
    stdin_open: true
    tty: true

  dakosys-updater:
    image: ghcr.io/sahara101/dakosys:latest
    container_name: dakosys-updater
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /kometa:/kometa
    restart: unless-stopped
    command: daemon
